# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Varun Srivastava
title: Stanford EE
email: vsriva@stanford.edu
phone: +1 (719)-430-5204
# website: Your website (eg. https://google.com)(optional)
description: >- # this means to ignore newlines until "baseurl:"
  I am Varun Srivastava, a graduate student at Stanford University pursuing a Masters in Electrical Engineering. A graduate of IIT Delhi, my main interests lie in establishing the mathematical foundations of and accelerating Deep learning algorithms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: favicon.ico

# Social links
# twitter_username: jekyllrb
github_username:  VarunSrivastavaIITD
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: varun-srivastava-2a7a76193
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Varun Srivastava, a graduate student at Stanford University pursuing a Masters in Electrical Engineering. A graduate of IIT Delhi, my main interests lie in establishing the mathematical foundations of and accelerating Deep learning algorithms, and their applications such as

  - Biomedical (Photoplethysmography)
  - Computer Vision
  - Sequence Analysis and Generation
  
   My future research endeavours aim to provide a firmer footing to algorithms used to train neural networks by using information theoretic tools and optimization theory. In practice, this may manifest as optimizations to training and inference procedures both at an algorithmic and system implementation levels.

   In the past I have had the fortune to work in highly integrated teams, which have allowed me to not only bring my projects to successful completion, but also thrive in an open work environment that fosters both personal growth, leadership abilities and teamwork. My mission is to develop sound principles for (machine) learning algorithms that have cross cutting real world impact across a range of domains from medicine to engineering.

# Projects Section
projects_title: Projects and Publications #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love to read fantasy during my leisure time. A short (and incomplete) list of my favoured authors includes Patrick Rothfuss, Brandon Sanderson, Brent Weeks, Neil Gaiman, N.K. Jemisin. You can also find me tinkering with the shiniest deep learning framework on the block (PyTorch at the moment) with my trusty cup of tea.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
